#pragma once
import "oaidl.idl";
import "ocidl.idl";

//为了能在接口中传递结构体，所以有该文件的存在。
//河段的固定参数的结构体，不含时变参数，LAI,WaterEva
//注意：原来的坦化系数用ｘ表示，结果和经度Ｘ冲突，所以很奇怪，改之．

struct Para
{
	//constanat p muskingum
	float WaveCoefficient; //波速系数
	float TanHua;//坦化系数
	float WetRadius; //湿周

	//Middle X
	float X;
	//Middle Y
	float Y;

	//沟道
	float StreamSlope; //坡度
	float StreamLength; //长
	float Manning; //n
	float RiverManning;//20051218 李铁键 沟道的糙率
	float m;//边坡系数,最初取4

	//20080306,xiaofc,增加沟坡坡度字段，专门用于计算重力侵蚀
	float GullySlope; //角度
	float DrainingArea;//汇水面积

	//土壤土质
	float D50;
	int LandUse;
	int SoilType;
	
	//需要通过矩阵转换的
	float Sita1,Sita2,MSita1,MSita2,DSita1,DSita2;//孔隙率
	float UDepth,DDepth;
	float PKH1,PKH2,PKV0,PKV1,PKV2;//渗透力
	float I0;
	float ErosionK;

	//David 坡面产沙模型参数
	float ErosionK1;
	float ErosionK2;
	float ErosionBeta1;
	float ErosionBeta2;
	//左
	float SlopeL;
	float LengthL;
	float AreaL;

	//右
	float SlopeR;
	float LengthR;
	float AreaR;

	//源
	float SlopeS;
	float LengthS;
	float AreaS;

	float A;
	float UElevation;
	float DElevation;
};

struct BSCode 
{
	long RegionGrade;
	unsigned long long RegionIndex;
	long Length;
	unsigned long long Value;
};
